name: Flutter CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      KEY_JKS: ${{ secrets.KEY_JKS }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}

    steps:
    
    - uses: actions/checkout@v1
    
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # if you use ndk
    - run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.1.6352462" --sdk_root=${ANDROID_SDK_ROOT}
    
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # or 'dev' or 'beta'
    
    - run: echo KEY_JKS | base64 -d > android/app/upload.jks
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --release --split-per-abi
    
    - uses: actions/upload-artifact@v2
      with:
        path: |
          build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          build/app/outputs/flutter-apk/app-x86_64-release.apk
